" MacVIM / GUI settings
set lines=126 columns=133 " 2 (signs) + 4+1 (numberwidth) + 100 + 1 + 25 (NERDTree)
set guifont=Menlo:h10

" colorscheme solarized
" set t_Co=256
"set transparency=6

" agimrLtT → acem
set guioptions+=c go+=e go-=g go-=i go-=r go-=L go-=t go-=T
