" MacVIM / GUI settings
set lines=126 columns=131 " 1+25 (NERDTree width) + 100 + 4 (numberwidth) + 1 (margin)
set guifont=Menlo:h10

" colorscheme solarized
" set t_Co=256
"set transparency=6

" agimrLtT → acem
set guioptions+=c go+=e go-=g go-=i go-=r go-=L go-=t go-=T
