 # :vim: set ft=ansible :

 - tags: xz-ws-twag
   block:
    - name: Create xz.ws twag app
      dokku_app:
         app: xz.ws-twag

    - name: Set domain for xz.ws twag app
      dokku_domains:
         app: xz.ws-twag
         domains: xz.ws
         state: set

    - name: Configure environment for xz.ws twag app
      vars:
         vault: Elliott - Work-visible
         db_item: Neon PostgreSQL - twag (dev/ec; twag_admin@twag)
         api_item: Notion API key - twag (xz.ws)
      dokku_config:
         app: xz.ws-twag
         config:
            DATABASE_URL: "{{ lookup('onepassword', db_item, field='connection string', vault=vault) }}"
            NOTION_TOKEN: "{{ lookup('onepassword', api_item, field='credential', vault=vault) }}"
            NOTION_THINGS_DB: "{{ lookup('onepassword', api_item, section='things DB', field='UUID', vault=vault) }}"
            NOTION_THINGS_COLUMN_NAME: "{{ lookup('onepassword', api_item, section='things DB', field='column name', vault=vault)
               }}"
            NOTION_CONTAINERS_DB: "{{ lookup('onepassword', api_item, section='containers DB', field='UUID', vault=vault)
               }}"
            NOTION_CONTAINERS_COLUMN_NAME: "{{ lookup('onepassword', api_item, section='containers DB', field='column name',
               vault=vault) }}"
            RUST_LOG: info
            RUST_FMT: json

    - name: Configure caddy-docker-proxy labels for xz.ws twag app
      dokku_docker_options:
         app: xz.ws-twag
         phase: deploy
         option: >-
            --label=caddy='xz.ws' --label=caddy.reverse_proxy={%raw%}'/* {{upstreams http 3000}}'{%endraw%}
         state: present
      notify: "dokku-tweaks : Restart caddy proxy"
