exclude:
 - Infrastructure/Vendor/
 - Infrastructure/Windmill/wmill-lock.yaml

formatter:
   indent: 3
   array_indent: 1
   indent_root_array: true # prospective, needs braydonk/yaml#20
   max_line_length: 120
   retain_line_breaks_single: true
   trim_trailing_whitespace: true
   eof_newline: true
