windmill_base_url: "https://{{ server_domain }}"

windmill_network_name: windmill-network

windmill_server_name: windmill-server

windmill_worker_name: windmill-worker
windmill_worker_count: 3

windmill_lsp_name: windmill-lsp
