# :vim: set ft=ansible :

 - tags:
    - always
    - connection-fallback
   block:

    - when: ansible_verbosity > 1
      ansible.builtin.debug:
         var: ssh_port_retry_count

    - ansible.builtin.set_fact:
         ssh_port_retry_count: "{{ ((ssh_port_retry_count | default(0)) | int) + 1 }}"

    - ansible.builtin.set_fact:
         target_host: "{{ ansible_host }}"

    - name: "Test for (configured) SSH port availability w/ netcat ({{ ansible_port }})"
      delegate_to: localhost
      ansible.builtin.command: nc -z -w2 {{ target_host }} {{ ansible_port }}
      register: ssh_port_nctest
      changed_when: false
      ignore_errors: true

    - name: Test default SSH port instead
      when: ssh_port_nctest.failed
      ansible.builtin.include_tasks: 2_check_default_ssh_port.yaml

   rescue:
    - when: ssh_port_retry_count|int > 10
      ansible.builtin.fail:
         msg: "Giving up after too many retries (attempts: {{ ssh_port_retry_count }})"

    - name: Sleep for 30 seconds before retrying
      ansible.builtin.pause:
         seconds: 30

    - ansible.builtin.include_tasks: 1_wait_for_ssh_port.yaml
