# :vim: set ft=ansible :

 - name: Print user IDs and port before port-fallback
   ansible.builtin.debug:
      verbosity: 1
      msg: |
         ansible_port: {{ ansible_port | d('unset') }};
         ansible_user: {{ ansible_user | d('unset') }};
         remote_user: {{ remote_user | d('unset') }}

 - name: Save previous SSH port for later restoration
   ansible.builtin.set_fact:
      ansible_port_to_restore: "{{ ansible_port }}"

 - name: Fallback to default SSH port
   ansible.builtin.set_fact:
      ansible_port: 22

 - name: Print user IDs and port after port-fallback
   ansible.builtin.debug:
      verbosity: 1
      msg: |-
         ansible_port: {{ ansible_port | d('unset') }};
         ansible_user: {{ ansible_user | d('unset') }};
         remote_user: {{ remote_user | d('unset') }}
