 # code: language=ansible
 - name: Print 'before' values for user IDs
   ansible.builtin.debug:
      msg: |
         ansible_user: {{ ansible_user | d('unset') }};
         remote_user: {{ remote_user | d('unset') }}

 - name: Test SSH connection to remote host
   ansible.builtin.ping:
   ignore_unreachable: true
   ignore_errors: true
   register: pingtest

 - name: Ignore errors from the intentional ping-test
   ansible.builtin.meta: clear_host_errors

 - name: Proceed to reauthenticate as root and setup user if SSH failed
   ansible.builtin.include_tasks: setup_user.yaml
   when: pingtest is failed | d(pingtest.unreachable) | d(false)

 - name: Gather facts for the first time
   ansible.builtin.setup:
   when: pingtest is succeeded
