 # code: language=ansible
 - name: Test SSH connection to remote host
   ansible.builtin.ping:
   ignore_unreachable: true
   ignore_errors: true
   register: pingtest
   tags:
    - always
    - ping-gather

 - name: Print pingtest results
   ansible.builtin.debug:
      verbosity: 1
      var: pingtest

 - name: Ignore errors from the intentional ping-test
   ansible.builtin.meta: clear_host_errors
   tags:
    - always
    - ping-gather

 - name: Handle connection failure
   until: not (pingtest.unreachable is defined or pingtest.rc != 0)
   block:
    - name: Test for configured SSH port availability w/ netcat
      delegate_to: localhost
      ansible.builtin.command: nc -z -w5 {{ inventory_hostname }} {{ ansible_port }}
      register: nctest
      failed_when: nctest.stdout.find('failed') != -1
      changed_when: never
      ignore_errors: true

 - name: Proceed to reauthenticate as root and setup user if SSH failed
   ansible.builtin.include_tasks: setup_user.yaml
   when: pingtest.unreachable is defined or pingtest.rc != 0

 - name: Gather facts over user-SSH
   ansible.builtin.setup:
   when: not (pingtest.unreachable is defined or pingtest.rc != 0)
   tags:
    - always
    - ping-gather
