# :vim: set ft=ansible :

 - tags:
    - always
    - ping-gather
    - connection-fallback
   block:

    - name: Test SSH connection to remote host
      ansible.builtin.ping:
      ignore_unreachable: true
      register: initial_pingtest

    - ansible.builtin.fail:
      when: initial_pingtest.unreachable is defined or initial_pingtest.failed

   rescue:

    - name: Handle initial ping failure
      ansible.builtin.debug:
         var: initial_pingtest
      changed_when: true
      notify: Try connection fallbacks
      tags:
       - always
       - connection-fallback

    - ansible.builtin.meta: flush_handlers

 - name: Gather facts
   ansible.builtin.setup:
   tags:
    - always
    - ping-gather
