 # code: language=ansible
 - debug:
      msg: |
         ansible_user: {{ ansible_user | d('unset') }};
         remote_user: {{ remote_user | d('unset') }}

 - action: ping
   ignore_unreachable: true
   ignore_errors: yes
   register: pingtest

 - meta: clear_host_errors

 - name: proceed to reauthenticate as root and setup user if ssh failed
   include_tasks: setup_user.yaml
   when: pingtest.failed | d(pingtest.unreachable) | d(false)
