# code: language=ansible

 - name: Test SSH connection to remote host
   ansible.builtin.ping:
   ignore_unreachable: true
   ignore_errors: true
   register: initial_pingtest
   tags:
    - always
    - ping-gather

 - ansible.builtin.debug:
      verbosity: 1
      var: initial_pingtest
   tags:
    - always
    - ping-gather

 - name: Handle connection failure
   when: initial_pingtest.unreachable is defined or initial_pingtest.rc != 0
   block:

    - name: Wait for either SSH port (configured or default) to become available
      ansible.builtin.include_tasks: 1_wait_for_ssh_port.yaml

    - name: "Test for (configured) SSH user availability w/ builtin.ping: ({{ ansible_user }}) on port ({{ ansible_port }})"
      ansible.builtin.ping:
      ignore_unreachable: true
      ignore_errors: true
      register: known_port_pingtest

    - ansible.builtin.debug:
         verbosity: 1
         var: known_port_pingtest

    - name: Fallback to root SSH user
      when: known_port_pingtest.unreachable is defined or known_port_pingtest.rc != 0
      ansible.builtin.include_tasks: 3_fallback_to_root_ssh_user.yaml

    - ansible.builtin.meta: clear_host_errors

# --- --- ---

 - name: Gather facts over user-SSH
   ansible.builtin.setup:
   tags:
    - always
    - ping-gather

 - name: Setup user
   ansible.builtin.include_tasks: 4_setup_admin_user.yaml
