 # code: language=ansible
 - name: Wait for sshd on remote host to come up
   ansible.builtin.wait_for_connection:
      sleep: 10
      timeout: 360

 - name: Gather facts over root-SSH
   ansible.builtin.setup:

 - name: Run HTSALSWA 'requirements' role for actual setup
   ansible.builtin.include_tasks:
      file: ../../../Vendor/HTSALSWA/roles/requirements/tasks/main.yml

 - name: Reauthenticate as normal admin user
   ansible.builtin.set_fact:
      ansible_user: "{{ ansible_user_to_restore }}"
      ansible_ssh_pass: "" # unset password

 - name: Reset connection
   ansible.builtin.include_tasks: reset_connection.yaml

 - name: Print 'after' values for user IDs
   ansible.builtin.debug:
      verbosity: 1
      msg: |-
         ansible_user: {{ ansible_user | d('unset') }};
         remote_user: {{ remote_user | d('unset') }}
