# :vim: set ft=ansible :

 - tags: elliottcable.name
   block:

    - name: Create an elliottcable.name app
      dokku_app:
         app: elliottcable.name

    - name: Sync elliottcable.name repo
      dokku_clone:
         app: elliottcable.name
         repository: https://github.com/ELLIOTTCABLE/elliottcable.name.git
         version: main
         build: false
      register: elliottcable_name_sync

    - name: Rebuild elliottcable.name if repo changed
      ansible.builtin.command: dokku ps:rebuild elliottcable.name
      when: elliottcable_name_sync.changed
      changed_when: true

    - name: Set elliottcable.name domain
      dokku_domains:
         app: elliottcable.name
         domains: elliottcable.name
         state: present
