# Start AeroSpace at login
start-at-login = true

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide.html#assign-workspaces-to-monitors
gaps.inner.horizontal = 7
gaps.inner.vertical = 7
gaps.outer.left = 7
gaps.outer.bottom = 7
gaps.outer.top = 7
gaps.outer.right = 7

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide.html#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands.html

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands.html#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#layout
alt-comma = 'layout accordion horizontal vertical'
alt-slash = 'layout tiles horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#focus
alt-h = 'focus --boundaries all-monitors-outer-frame left'
alt-j = 'focus --boundaries all-monitors-outer-frame down'
alt-k = 'focus --boundaries all-monitors-outer-frame up'
alt-l = 'focus --boundaries all-monitors-outer-frame right'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#resize
alt-shift-minus = 'resize smart -100'
alt-equal = 'resize smart +100'
alt-shift-equal = 'resize smart +100'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus-monitor
alt-t = 'focus-monitor left'
alt-g = 'focus-monitor down'
alt-d = 'focus-monitor right'
alt-b = 'focus-monitor up'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-monitor
alt-shift-t = ['move-node-to-monitor left', 'focus-monitor left']
alt-shift-g = ['move-node-to-monitor down', 'focus-monitor down']
alt-shift-d = ['move-node-to-monitor right', 'focus-monitor right']
alt-shift-b = ['move-node-to-monitor up', 'focus-monitor up']

# See: https://nikitabobko.github.io/AeroSpace/commands.html#workspace
alt-shift-0 = 'workspace 0'
alt-shift-1 = 'workspace 1'
alt-shift-2 = 'workspace 2'
alt-shift-3 = 'workspace 3'
alt-shift-4 = 'workspace 4'
alt-shift-5 = 'workspace 5'
alt-shift-6 = 'workspace 6'
alt-shift-7 = 'workspace 7'
alt-shift-8 = 'workspace 8'
alt-shift-9 = 'workspace 9'
alt-u = 'workspace U'
alt-y = 'workspace Y'
alt-q = 'workspace Q'
alt-w = 'workspace W'
alt-f = 'workspace F'
alt-p = 'workspace P'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#move-node-to-workspace
alt-0 = 'move-node-to-workspace 0'
alt-1 = 'move-node-to-workspace 1'
alt-2 = 'move-node-to-workspace 2'
alt-3 = 'move-node-to-workspace 3'
alt-4 = 'move-node-to-workspace 4'
alt-5 = 'move-node-to-workspace 5'
alt-6 = 'move-node-to-workspace 6'
alt-7 = 'move-node-to-workspace 7'
alt-8 = 'move-node-to-workspace 8'
alt-9 = 'move-node-to-workspace 9'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-y = 'move-node-to-workspace Y'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-f = 'move-node-to-workspace F'
alt-shift-p = 'move-node-to-workspace P'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands.html#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands.html#mode
alt-shift-o = 'mode service'
alt-shift-slash = 'mode join'
alt-shift-e = 'mode workspace'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#binding-modes
[mode.service.binding]
f = [
   'layout floating tiling',
   'mode main',
] # Toggle between floating and tiling layout
alt-shift-f = [
   'layout floating tiling',
   'mode main',
] # Toggle between floating and tiling layout
x = ['fullscreen', 'mode main']
alt-shift-x = ['fullscreen', 'mode main']
z = ['flatten-workspace-tree', 'mode main'] # reset layout
alt-shift-z = ['flatten-workspace-tree', 'mode main'] # reset layout
r = ['reload-config', 'mode main']
alt-shift-r = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
alt-shift-backspace = ['close-all-windows-but-current', 'mode main']

# 'join' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide.html#binding-modes
[mode.join.binding]
h = ['join-with left', 'mode main']
alt-shift-h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
esc = 'mode main'

[mode.workspace.binding]
h = ['move-workspace-to-monitor prev', 'mode main']
alt-shift-h = ['move-workspace-to-monitor prev', 'mode main']
l = ['move-workspace-to-monitor next', 'mode main']
alt-shift-l = ['move-workspace-to-monitor next', 'mode main']
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.culturedcode.ThingsMac'
if.window-title-regex-substring = 'tags'
run = 'layout tiling'

[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam.helper'
run = 'layout tiling'

# Colemak mapping
[key-mapping.key-notation-to-key-code]
f = 'e'
p = 'r'
g = 't'
j = 'y'
l = 'u'
u = 'i'
y = 'o'
semicolon = 'p'

a = 'a'
r = 's'
s = 'd'
t = 'f'
d = 'g'
h = 'h'
n = 'j'
e = 'k'
i = 'l'
o = 'semicolon'

k = 'n'
m = 'm'
