ALTER TABLE folder DISABLE ROW LEVEL SECURITY;
ALTER TABLE account DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit DISABLE ROW LEVEL SECURITY;
ALTER TABLE queue DISABLE ROW LEVEL SECURITY;
ALTER TABLE completed_job DISABLE ROW LEVEL SECURITY;

ALTER TABlE resource DISABLE ROW LEVEL SECURITY;
ALTER TABlE script DISABLE ROW LEVEL SECURITY;
ALTER TABlE variable DISABLE ROW LEVEL SECURITY;
ALTER TABlE schedule DISABLE ROW LEVEL SECURITY;
ALTER TABlE flow DISABLE ROW LEVEL SECURITY;

ALTER TABLE usr_to_group DISABLE ROW LEVEL SECURITY;
ALTER TABLE app DISABLE ROW LEVEL SECURITY;
ALTER TABLE capture DISABLE ROW LEVEL SECURITY;
