[plugins]
cabal = "https://github.com/sestrella/asdf-ghcup.git"
hls = "https://github.com/sestrella/asdf-ghcup.git"

[tools]
deno = "latest"
dotnet = "latest"
golang = "latest"
lua = "latest"
nodejs = "latest"
opam = "latest"
postgres = "latest"
purescript = "latest"
python = "latest"
racket = "latest"
ruby = "latest"
rust = "latest"
usage = "latest"

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{ get_env(name='XDG_CONFIG_HOME', default='~/.config') }}/mise/default-npm-packages"

[settings.python]
default_packages_file = "{{ get_env(name='XDG_CONFIG_HOME', default='~/.config') }}/mise/default-pip-packages"
compile = true
