# :vim: set ft=ansible :

all:
   hosts:
      berit.ell.io: null # varying IP, testing instance
      euphemios.ell.io: null # 69.197.191.2
      eurydice.ell.io:
         ansible_host: 45.76.230.26

unified:
   hosts:
      # used for testing
      berit.ell.io:
         ansible_host: null # replace w/ temporary IP
