- name: All hosts idk
  hosts: all

  gather_facts: false
  pre_tasks:
     - name: Wait for SSH to come up
       ansible.builtin.wait_for_connection:
          delay: 5
          timeout: 1800
     - name: Gather facts for the first time
       ansible.builtin.setup:

  roles:
     - role: aisbergg.acl
       become: true
     - role: geerlingguy.docker
       become: true
     - role: dokku_bot.ansible_dokku
       become: true
     - deno
     - windmill

  vars:
     dokku_packages_state: latest
     dokku_hostname: with.ec
     dokku_manage_nginx: false
     server_domain: windmill.with.ec
     db_pass: "{{ lookup('env', 'DB_PASS') }}"
     db_host: "{{ lookup('env', 'DB_HOST') }}"
     db_port: "{{ lookup('env', 'DB_PORT') }}"
     db_name: "{{ lookup('env', 'DB_NAME') }}"
     db_url: "postgres://windmill_admin:{{ db_pass }}@{{ db_host }}:{{ db_port }}/{{ db_name }}"
     caddy_letsencrypt_email: "letsencrypt-automated@from.ec"
     caddy_letsencrypt_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
     deno_root: /usr/local
     python_path: /usr/bin/python3
