- name: All hosts idk
  hosts: all
  roles:
     - role: aisbergg.acl
       become: true
     - role: geerlingguy.docker
       become: true
     - role: dokku_bot.ansible_dokku
       become: true
     - deno
     - windmill

  vars:
     dokku_packages_state: latest
     dokku_hostname: with.ec
     dokku_manage_nginx: false
     server_domain: windmill.with.ec
     database_url: "postgres://{{ lookup('env', 'DATABASE_URL') }}/windmilldb"
     caddy_letsencrypt_email: "letsencrypt-automated@elliottcable.com"
     caddy_letsencrypt_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
     deno_root: /usr/local
     python_path: /usr/bin/python3
