# :vim: set ft=ansible :

 - tags: dokku.proxy
   block:

    - name: Check if the nginx proxy is enabled
      ansible.builtin.command: /lib/systemd/systemd-sysv-install is-enabled nginx
      register: nginx_enabled
      failed_when: false
      changed_when: false

    - name: Deactivate the nginx proxy
      # TODO: Define changed/success using:
      #     $ /lib/systemd/systemd-sysv-install is-enabled nginx
      ansible.builtin.command: dokku nginx:stop
      when: nginx_enabled.rc == 0

    - name: Check the proxy-selection configuration
      ansible.builtin.command: dokku proxy:report
      register: proxy_report
      changed_when: false

    - name: Select Caddy as the global proxy
      when: "'Proxy computed type:           caddy' not in proxy_report.stdout"
      ansible.builtin.command: dokku proxy:set --global caddy
      notify: Restart caddy proxy

    - name: Check the caddy configuration
      tags: dokku.certs
      ansible.builtin.command: dokku caddy:show-config
      register: caddy_config_report
      changed_when: false

    - name: Configure caddy's letsencrypt e-mail settings
      tags: dokku.certs
      when: caddy_letsencrypt_email is defined and not (caddy_letsencrypt_email in caddy_config_report.stdout)
      ansible.builtin.command: dokku caddy:set --global letsencrypt-email {{ caddy_letsencrypt_email | quote }}
      notify: Restart caddy proxy

    - name: Configure caddy's letsencrypt server-address settings
      tags: dokku.certs
      when: caddy_letsencrypt_server is defined and not (caddy_letsencrypt_server in caddy_config_report.stdout)
      ansible.builtin.command: dokku caddy:set --global letsencrypt-server {{ caddy_letsencrypt_server | quote }}
      notify: Restart caddy proxy
